---
spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
  datasource:
    initialization-mode: never
    schema: "classpath:sql/schema.sql"
    data: "classpath:sql/data.sql"
---
spring:
  profiles:
    active: test
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:reservations_test;Mode=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    sql-script-encoding: UTF-8
